version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/frontend_ksd
hooks:
  AfterInstall:
    - location: scripts/setup_docker.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
