describe('Registration ', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#registerform').click()
  })
  it('User can register if all fields are correct', () => {
    cy.get('#username').type('Tenuteppo')
    cy.get('#email').type('hehe@hehe.fi')
    cy.get('#firstname').type('Teppo')
    cy.get('#lastname').type('Tenuttaja')
    cy.get('#password').type('bigsikret')
    cy.get('#passwordConf').type('bigsikret')
    cy.get('#accept').check()
    cy.get('#register-button').click()
    cy.contains('Pääset luomaan uuden käyttäjän täällä')
  })
  it('User can not register a user with too short password', () => {
    cy.get('#username').type('Tenuteppo')
    cy.get('#firstname').type('Teppo')
    cy.get('#lastname').type('Tenuttaja')
    cy.get('#password').type('1234567')
    cy.get('#passwordConf').type('1234567')
    cy.get('#email').type('test@gmail.com')
    cy.get('#accept').check()
    cy.get('#register-button').click()
    cy.contains('Rekisteröityminen ei onnistunut')
  })
})
