describe('Settings ', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#loginform').click()
    cy.get('#email').type('hehe@hehe.fi')
    cy.get('#password').type('bigsikret{enter}')
    cy.get('#settings').click()
  })
  it('User can modify account settings successfully', () => {
    cy.get('#username').clear()
    cy.get('#username').type('testailija')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('testailija')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('koira')
    cy.get('#email').clear()
    cy.get('#email').type('test@gmail.com')
    cy.get('#update-button').click()
    cy.contains('Tervetuloa')
  })

  it('User can create date profile successfully', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')
    cy.get('#dateOfBirth').type('1917-12-06')
    cy.get('#location').select('UUSIMAA')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#bio').type('Jee jee jee')
    cy.get('#christianAndSingle').check()
    cy.get('#dateprofile-button').click()
    cy.contains('Tervetuloa')
  })
})
