describe('Settings ', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.intercept('POST', 'http://localhost:8082').as('updateAccount')
    cy.get('#loginform').click()
    cy.get('#username').type('test')
    cy.get('#password').type('testtest{enter}')
    cy.contains('Tervetuloa!')
    cy.get('#settings').click()
  })
  it('User can modify account settings successfully', () => {
    cy.get('#name').clear()
    cy.get('#name').type('testailija')
    cy.get('#first').clear()
    cy.get('#first').type('testailija')
    cy.get('#last').clear()
    cy.get('#last').type('koira')
    cy.get('#email').clear()
    cy.get('#email').type('test@gmail.com')
    cy.get('#update-button').click()
    cy.wait('@updateAccount')
    cy.contains('Tervetuloa')
  })
  it('User can update date profile successfully', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')

    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#bio').clear()
    cy.get('#bio').type('Jee jee jee')
    cy.wait('@updateAccount')
    cy.get('#dateprofile-button').click()
    cy.wait('@updateAccount')
    cy.contains('Tervetuloa')
  })
})
