describe('Settings ', () => {
  beforeEach(() => {
    cy.visit('http://localhost:3000/')
    cy.get('#loginform').click()
    cy.get('#email').type('hehe@hehe.fi')
    cy.get('#password').type('bigsikret{enter}')
    cy.get('#settings').click()
  })
  it('User can modify account settings successfully', () => {
    cy.get('#username').clear()
    cy.get('#username').type('testailija')
    cy.get('#firstname').clear()
    cy.get('#firstname').type('testailija')
    cy.get('#lastname').clear()
    cy.get('#lastname').type('koira')
    cy.get('#email').clear()
    cy.get('#email').type('test@gmail.com')
    cy.get('#update-button').click()
    cy.contains('Tervetuloa')
  })

  it('User can create date profile successfully', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')
    cy.get('#dateOfBirth').type('1917-12-06')
    cy.get('#location').select('UUSIMAA')
    cy.get('#regions').type('SATAKUNTA{enter}{enter}')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#bio').type('Jee jee jee')
    cy.get('#christianAndSingle').check()
    cy.get('#dateprofile-button').click()
    cy.contains('Tervetuloa')
  })
  it('User can create date profile with valid birth date, case 1', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')
    cy.get('#dateOfBirth').type('1900-01-01')
    cy.get('#location').select('UUSIMAA')
    cy.get('#regions').type('SATAKUNTA{enter}{enter}')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#bio').type('Jee jee jee')
    cy.get('#christianAndSingle').check()
    cy.get('#dateprofile-button').click()
    cy.contains('Tervetuloa')
  })
  it('User cannot create date profile with invalid birth day, case 1', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')
    cy.get('#dateOfBirth').type('1899-12-31')
    cy.get('#location').select('UUSIMAA')
    cy.get('#regions').type('SATAKUNTA{enter}{enter}')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#bio').type('Jee jee jee')
    cy.get('#christianAndSingle').check()
    cy.get('#dateprofile-button').click()
    cy.contains('Muokkaa perusasetuksia')
  })
  it('User can create date profile with valid birth date, case 2', () => {
    cy.get('#gender').select('FEMALE')
    cy.contains('Nainen')
    cy.get('#gender').select('MALE')
    cy.contains('Mies')
    cy.get('#dateOfBirth').type('2003-06-29')
    cy.get('#location').select('UUSIMAA')
    cy.get('#regions').type('SATAKUNTA{enter}{enter}')
    cy.get('#status').select('DIVORCED')
    cy.contains('Eronnut')
    cy.get('#status').select('SINGLE')
    cy.contains('Sinkku')
    cy.get('#bio').type('Jee jee jee')
    cy.get('#christianAndSingle').check()
    cy.get('#dateprofile-button').click()
    cy.contains('Tervetuloa')
  })
  it('User can see other users date profile', () => {
    cy.visit('http://localhost:3000/b8342c78-7313-4c5e-a45f-3f931c1366b0')
    cy.contains('deittiprofiili')
    cy.contains('Sukupuoli')
    cy.contains('Sijainti')
    cy.contains('Siviilisääty')
    cy.contains('Kuvaus')
  })

  it('User can see own settings but not others', () => {
    cy.visit('http://localhost:3000/7561c5a6-7566-4097-8453-c9254414e397')
    cy.contains('Etunimi')
    cy.contains('Sukunimi')

    cy.visit('http://localhost:3000/b8342c78-7313-4c5e-a45f-3f931c1366b0')
    cy.contains('Sukupuoli')
    cy.contains('Sijainti')
    cy.contains('Etunimi').should('not.exist')
    cy.contains('Sukunimi').should('not.exist')
    cy.contains('Nimimerkki').should('not.exist')
    cy.contains('Sähköposti').should('not.exist')
  })
})
