const regions = [
  { value: 'AHVENANMAA', label: 'Ahvenanmaa' },
  { value: 'ETELAPOHJANMAA', label: 'Etelä-Pohjanmaa' },
  { value: 'ETELASAVO', label: 'Etelä-Savo' },
  { value: 'KAINUU', label: 'Kainuu' },
  { value: 'KANTAHAME', label: 'Kanta-Häme' },
  { value: 'KESKIPOHJANMAA', label: 'Keski-Pohjanmaa' },
  { value: 'KESKISUOMI', label: 'KeskiSuomi' },
  { value: 'KYMENLAAKSO', label: 'Kymenlaakso' },
  { value: 'LAPPI', label: 'Lappi' },
  { value: 'PIRKANMAA', label: 'Pirkanmaa' },
  { value: 'POHJANMAA', label: 'Pohjanmaa' },
  { value: 'POHJOISKARJALA', label: 'Pohjois-Karjala' },
  { value: 'POHJOISPOHJANMAA', label: 'Pohjois-Pohjanmaa' },
  { value: 'POHJOISSAVO', label: 'Pohjois-Savo' },
  { value: 'PAIJATHAME', label: 'Päijät-Häme' },
  { value: 'SATAKUNTA', label: 'Satakunta' },
  { value: 'UUSIMAA', label: 'Uusimaa' },
  { value: 'VARSINAISSUOMI', label: 'Varsinais-Suomi' },
]
export default regions
