name: Test Automation

on:
  push:
    branches-ignore: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run Jest tests
        run: yarn run test
      - name: Run ESLint
        run: yarn run lint