name: Test Automation

on:
  push:
    branches-ignore: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Run Jest tests
        run: npm run test
      - name: Run ESLint
        run: npm run lint
      - name: Cypress-run
        uses: cypress-io/github-action@v2
        with:
          start: npm start, npm run dev --prefix ../../user-api/
          working-directory: src
          wait-on: 'http://localhost:8082/, http://localhost:3000'
          browser: chrome
          wait-on-timeout: 20
          record: true
      - name: Data to codecov
        run: bash <(curl -s https://codecov.io/bash)
