name: Test Automation

on:
  push:
    branches-ignore: [main]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Run Jest tests
        run: yarn run test
      - name: Run ESLint
        run: yarn run lint
      - name: Cypress-run
        uses: cypress-io/github-action@v2
        with:
          start: yarn run start:test
          wait-on: 'http://localhost:3000'
          browser: chrome
          wait-on-timeout: 20
          record: false